### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by Rotscha** [sirinsidiator/ESO-AetheriusBadgeFilter#3]
Translation to various languages (DE/FR/JP/RU). Affects settings menu, tooltips and coming dialogues

**Comment by sirinsidiator** [comment]
I suggest we do it like in my other addons and use a local table instead of the ZOS way.
The different languages are put in separate files and only the current language + en (as a fallback) is loaded.

It may also be worth to consider allowing localized labels in the badge data files for guilds that support more than one language, but that's probably a whole feature on its own.
